package tests;// Generated by Selenium IDE

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import common.CommonFunctions;
import model.GroupData;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.function.Supplier;
import java.util.stream.Stream;


public class GroupCreationTests extends TestBase {
  public static List<GroupData> groupProvider() throws IOException {
    var result = new ArrayList<GroupData>();
//    for (var name : List.of("", "group name")) {
//      for (var header : List.of("", "group header")) {
//        for (var footer : List.of("", "group footer")) {
//            result.add(new GroupData().withName(name).withHeader(header).withFooter(footer));
//        }
//      }
//    }
    var json = "";
    try (var reader = new FileReader("groups.json");
         var breader = new BufferedReader(reader)
    ) {
        var line = breader.readLine();
        while (line != null) {
            json = json + line;
            line = breader.readLine();
        }
    }
    //var json = Files.readString(Paths.get("groups.json"));
    ObjectMapper mapper = new ObjectMapper();
    var value = mapper.readValue(json, new TypeReference<List<GroupData>>() {});
    result.addAll(value);
    return result;
  }

  public static Stream<GroupData> randomGroups() {
      Supplier<GroupData> randomGroup = ()  -> new GroupData()
              .withName(CommonFunctions.randomString(10))
              .withHeader(CommonFunctions.randomString(20))
              .withFooter(CommonFunctions.randomString(30));
    return Stream.generate(randomGroup).limit(1);
  }

//  @ParameterizedTest
//  @MethodSource("groupProvider")
//  public void canCreateMultipleGroupsTest(GroupData group) {
//    int groupCount = app.groups().getCount();
//    app.groups().createGroup(group);
//    int newGroupCount = app.groups().getCount();
//    Assertions.assertEquals(groupCount+1, newGroupCount);
//  }

  @ParameterizedTest
  @MethodSource("randomGroups")
  public void canCreateGroup(GroupData group) {
    var oldGroups = app.hbm().getGroupList();
    app.groups().createGroup(group);
    var newGroups = app.hbm().getGroupList();
    var extraGroups = newGroups.stream().filter(g -> !oldGroups.contains(g)).toList();
    var newId = extraGroups.getFirst().id();

    var expectedList = new ArrayList<>(oldGroups);
    expectedList.add(group.withId(newId));
    Assertions.assertEquals(Set.copyOf(newGroups), Set.copyOf(expectedList));
  }

//  @Test
//  public void canCreateGroupTest() {
//    var oldGroups = app.groups().getList();
//    var newGroup = new GroupData().withName("New Group").withHeader("Header").withFooter("Footer");
//
//    app.groups().createGroup(newGroup);
//    var newGroups = app.groups().getList();
//
//    var expectedList = new ArrayList<>(oldGroups);
//    // определяем, какой именно объект появился в списке
//    var created = newGroups.stream()
//            .filter(g -> !oldGroups.contains(g))
//            .findFirst()
//            .orElseThrow();
//    expectedList.add(created);
//
//    expectedList.sort((a, b) -> a.name().compareTo(b.name()));
//    newGroups.sort((a, b) -> a.name().compareTo(b.name()));
//
//    Assertions.assertEquals(expectedList, newGroups);
//  }

  public static List<GroupData> negativeGroupProvider() {
    var result = new ArrayList<GroupData>(List.of(
            new GroupData("", "group name'", "", "")));
    return result;
  }

  @ParameterizedTest
  @MethodSource("negativeGroupProvider")
  public void canNotCreateGroupTest(GroupData group) {
    int groupCount = app.groups().getCount();
    app.groups().createGroup(group);
    int newGroupCount = app.groups().getCount();
    Assertions.assertEquals(groupCount, newGroupCount);
  }

}
